#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# cndbundle.py
# Description:
# -----------------------------------------------------------------------------
#
# Started on <sáb 01-08-2026 23:44:30.597635006 (1785620670)>
# Carlos Linares López <carlos.linares@uc3m.es>
#

"""
Definition of a bundle of files
"""

# imports
# -----------------------------------------------------------------------------
import re
import shutil

from pathlib import Path

import cndmetadata
import utils

# globals
# -----------------------------------------------------------------------------

# default logger
LOGGER = utils.LOGGER

# regular expressions

# the following regular expression is used to validate npancakes and npuzzles
RE_VALIDATE_1 = re.compile(r'(?P<size>[0-9]+)(?P<domain>[0-9a-zA-Z]+)\.(?P<project>[0-9a-zA-Z]+)-(?P<algorithm>[0-9a-zA-Z]+)\.(?P<variant>[0-9a-zA-Z-]+)\.(?P<ks>[0-9]+-[0-9]+).*')

# the following is used to match bundles from the roadmap domain
RE_VALIDATE_2 = re.compile(r'USA-road-d\.(?P<size>[A-Za-z]+)\.(?P<project>[0-9a-zA-Z]+)-(?P<algorithm>[0-9a-zA-Z]+)\.(?P<variant>[0-9a-zA-Z-]+)\.(?P<ks>[0-9]+-[0-9]+)')

# the following is used to match bundles from the maps domain
RE_VALIDATE_3 = re.compile(r'random512-(?P<size>[0-9]+)-0\.map\.(?P<project>[0-9a-zA-Z]+)-(?P<algorithm>[0-9a-zA-Z]+)\.(?P<variant>[0-9a-zA-Z-]+)\.(?P<ks>[0-9]+-[0-9]+)')

# info
INFO_MOVE = "Move   '{}' -> '{}'"
INFO_REMOVE = "Delete '{}'"

# warnings
WARNING_FILE_ALREADY_EXISTS = "The file '{}' already exists"

# errors
ERROR_UNKNOWN_SUFFIX = "The file '{}' has an unknown suffix"

# -----------------------------------------------------------------------------
# functions
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# validate_metadata
#
# given a file, return its metadata, in case it has any and None otherwise
# -----------------------------------------------------------------------------
def validate_metadata(path: Path) -> cndmetadata.CNDMetadata | None:
    """given a file, return its metadata, in case it has any and None otherwise"""

    # check whether this is a npancake/npuzzle bundle
    if (m := re.match(RE_VALIDATE_1, path.name)):

        # in case it is a pancake or puzzle, add the prefix "n-" to it before
        # because other scripts expect the domain to be written like that
        return cndmetadata.CNDMetadata("n-" + m.group('domain'),
                                       m.group('project'),
                                       m.group('algorithm'),
                                       m.group('variant'),
                                       m.group('size'),
                                       m.group('ks'))

    # if not, verify whether this comes from a roadmap
    if (m := re.match(RE_VALIDATE_2, path.name)):

        # in spite of the specific roadmap, the domain must be exactly roadmap
        # because that is the name that other scripts are expecting to find
        return cndmetadata.CNDMetadata("roadmap",
                                       m.group('project'),
                                       m.group('algorithm'),
                                       m.group('variant'),
                                       m.group('size'),
                                       m.group('ks'))

    # if not, finally check whether this is a map
    if (m := re.match(RE_VALIDATE_3, path.name)):

        # in spite of the specific map, the domain must be exactly maps
        # because that is the name that other scripts are expecting to find
        return cndmetadata.CNDMetadata("maps",
                                       m.group('project'),
                                       m.group('algorithm'),
                                       m.group('variant'),
                                       m.group('size'),
                                       m.group('ks'))

    # otherwise, return None as a way of signaling that this specific file is
    # not recognizes as part of any bundle
    return None
    

# -----------------------------------------------------------------------------
# CNDBundle
#
# A bundle contains all files generated by condor for one specific experiment
# -----------------------------------------------------------------------------
class CNDBundle:
    """A bundle contains all files generated by condor for one specific
    experiment

    """

    def __init__(self):
        """A bundle is created empty and files are added to it

        """

        # initialize a container for each specific file
        self._condor = self._sh = None
        self._err = self._log = self._out = None
        self._csv = None

        # enable a flag to determine whether this is a valid bundle, i.e., that
        # the csv file is not empty
        self._valid = False

        # and also a list with all files stored
        self._files = []

        # finally, create an index to iterate over all files of this bundle
        self._idx = 0
        
    def __iadd__(self, filepath: Path):
        """add a new file to this bundle"""

        # the new file is indexed by its type
        if filepath.name.endswith(".condor"):
            self._condor = filepath
            self._files.append(filepath)
        elif filepath.name.endswith(".sh"):
            self._sh = filepath
            self._files.append(filepath)
        elif filepath.name.endswith(".err"):
            self._err = filepath
            self._files.append(filepath)
        elif filepath.name.endswith(".log"):
            self._log = filepath
            self._files.append(filepath)
        elif filepath.name.endswith(".out"):
            self._out = filepath
            self._files.append(filepath)
        elif filepath.name.endswith(".csv"):
            self._csv = filepath
            self._files.append(filepath)

            # and check whether this is a valid .csv file
            self._valid = self._csv.stat().st_size > 0
        else:
            LOGGER.critical(ERROR_UNKNOWN_SUFFIX.format(filepath))
            raise ValueError(ERROR_UNKNOWN_SUFFIX.format(filepath))

        return self

    def __iter__(self):
        """Defines the simplest case for iterators"""

        self._idx = 0
        return self

    def __len__(self):
        """return the number of files in this bundle"""

        return len(self._files)
    
    def __next__(self):
        '''returns the next file in this bundle
        '''

        # if we did not reach the limit
        if self._idx < len(self._files):

            # return the file in the current position (after incrementing)
            file = self._files[self._idx]
            self._idx += 1
            return file

        # restart the iterator for subsequent invocations of it
        self._idx = 0

        # and stop the current iteration
        raise StopIteration()
    
    def is_complete(self) -> bool:
        """return True if this bundle contains files for all its types and False
           otherwise

        """

        return self._condor is not None and \
            self._sh is not None and \
            self._err is not None and \
            self._log is not None and \
            self._out is not None and \
            self._csv is not None

    def is_valid(self) -> bool:
        """return True if this is a valid bundle, i.e., it is complete with a
           non-empty csv file or it only contains the condor and sh files

        """

        return (self.is_complete() and self._valid) or \
            (self._condor is not None and \
             self._sh is not None and \
             self._err is None and \
             self._log is None and \
             self._out is None and \
             self._csv is None)

        return self._valid
    
    def list(self, metadata:cndmetadata.CNDMetadata):
        """simply shows the metadata of this bundle which is given as a param

        """

        LOGGER.info("{}".format(metadata))
                
    def move(self, metadata: cndmetadata.CNDMetadata, dry_run: bool, force: bool):
        """move all contents of this bundle to their respective corresponding
           directories. If dry_run is given, a message informing the action to
           take is shown and no action is taken. If force is given files are
           overwritten when being moved if necessary.

           the method receives the metadata because it needs it for moving csv
           files

        """

        # iterate through all files in this bundle
        for ifile in self:

            if ifile.suffix == ".csv":

                # the destination for the csv files has to be computed
                # separately and it results from the metadata of this bundle
                directory = metadata.get_data_dir()
                
            else:
            
                # determine the directory where this file should be put, 
                directory = Path.cwd() / "condor" / ifile.suffix[1:]

            # if and only if this bundle is bot complete and valid, then move its contents
            if self.is_complete() and self.is_valid():

                # first, if dry_run was given, ...
                if dry_run:
                    LOGGER.info(INFO_MOVE.format(ifile.name, directory))

                else:
                
                    # first, verify whether the destination file already exists
                    destination = directory / ifile.name

                    # in case the file already exists:
                    if destination.exists():

                        # then if force was not given, simply issue a warning
                        if not force:
                            LOGGER.warning(WARNING_FILE_ALREADY_EXISTS.format(destination))
                            continue

                        else:

                            # otherwise, remove it so that it is replaced by the new contents
                            destination.unlink()
                    
                    # otherwise create the destination directory in case it
                    # does not exist and move the file to its destination
                    # location
                    directory.mkdir(parents=True, exist_ok=True)
                    shutil.move(ifile, directory)

    def remove(self, dry_run: bool):
        """remove all files from this bundle. If dry_run is given, a message
        informing the action to take is shown and no action is taken.

        """

        # for every file in this bundle
        for ifile in self:
            
            # unless --dry-run was given
            if dry_run:
                LOGGER.info(INFO_REMOVE.format(ifile.name))
            else:
                ifile.unlink()    

                
# Local Variables:
# mode:python
# fill-column:80
# End:
