#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# cndconf.py
# Description:
# -----------------------------------------------------------------------------
#
# Started on <sáb 02-12-2023 19:10:41.971115483 (1701540641)>
# Carlos Linares López <carlos.linares@uc3m.es>
#

"""
Global definitions of filenames and its contents
"""

# globals
# -----------------------------------------------------------------------------

# the allowed domains are
VALID_DOMAINS = ['maps', 'n-pancake', 'n-puzzle', 'roadmap', 'roadmap-maps']

# specification of valid variants as a dictionary of domains
VALID_VARIANTS = {
    "maps": ["unit", "octile"],
    "n-pancake": ["unit", "heavy-cost"],
    "n-puzzle": ["unit", "heavy-cost"],
    "roadmap": ["unit", "dimacs"],
    "roadmap-maps": ["dimacs"],
}

# the allowed search algorithms are (for the projects considered: 'libksearch'
# and 'k-shortest-simple-paths'):
VALID_ALGORITHMS = ['BELA0', 'K0', 'mDijkstra', 'BELA*', 'K*', 'mA*', 'bBELA0', 'bBELA*', 'sBELA0', 'sBELA*', 'Yen', 'Feng', 'PNC', 'PNC*', 'SB', 'SB*', 'PSB', 'PSBv2', 'PSBv3']

# the allowed projects are
VALID_PROJECTS = ['libksearch', 'k-shortest-simple-paths']

# acronyms used for the projects
ACRONYM_PROJECTS = {

    'libksearch': "libksearch",
    'k-shortest-simple-paths': "kssp",
}

# the executables of each domain are defined next:
EXECUTABLE = {
    "maps": "map",
    "n-pancake": "npancake",
    "n-puzzle": "npuzzle",
    "roadmap": "roadmap",
    "roadmap-maps": "roadmap",
}

# the arguments of every executable are given next
ARGS = {

    "libksearch": {

        "maps": "--map domains/$domain/benchmark/$testfile.map --solver '$paramalgorithm' --file domains/$domain/benchmark/$testfile.test --variant '$variant' --k '$kspec' --summary --no-doctor --no-color --csv $filename.csv",
        "n-pancake": "--solver '$paramalgorithm' --file domains/$domain/benchmark/$testfile.test --variant '$variant' --k '$kspec' --summary --no-doctor --no-color --csv $filename.csv",
        "n-puzzle": "--solver '$paramalgorithm' --file domains/$domain/benchmark/$testfile.test --variant '$variant' --k '$kspec' --summary --no-doctor --no-color --csv $filename.csv",
        "roadmap": "--graph domains/$domain/benchmark/$testfile.gr --solver '$paramalgorithm' --file domains/$domain/benchmark/$testfile.test --variant '$variant' --k '$kspec' --summary --no-doctor --no-color --csv $filename.csv",
        "roadmap-maps": "--graph domains/$execdomain/benchmark/$testfile.gr --solver '$paramalgorithm' --file domains/$execdomain/benchmark/$testfile.test --variant '$variant' --k '$kspec' --summary --no-doctor --no-color --csv $filename.csv",
    },

    "k-shortest-simple-paths": {
        "roadmap": "--graph domains/$domain/benchmark/$testfile.gr --solver '$paramalgorithm' --file domains/$domain/benchmark/$testfile.test --variant '$variant' --k '$kspec' --csv $filename.csv",
        "roadmap-maps": "--graph domains/$execdomain/benchmark/$testfile.gr --solver '$paramalgorithm' --file domains/$execdomain/benchmark/$testfile.test --variant '$variant' --k '$kspec' --csv $filename.csv",
    },
}


# filenames are indexed by the domain name
FILENAME = {
    "maps": "$map.$project-$solver.$variant.$mink-$maxk",
    "n-pancake": "${size}pancake.$project-$solver.$variant.$mink-$maxk",
    "n-puzzle": "${nbtiles}puzzle.$project-$solver.$variant.$mink-$maxk",
    "roadmap": "$map.$project-$solver.$variant.$mink-$maxk",
    "roadmap-maps": "$map.$project-$solver.$variant.$mink-$maxk",
}

# template for the condor job submission files which depends on the type of
# project chosen
CONDOR_FILE = {
    'libksearch': """#
# File automatically generated by condor (ksearch/libksearch)
#
# Project: $project
# Domain: $domain
# Variant: $variant
# Solver: $algorithm
#
nice_user = True
notify_user = $user
notification = Always
getenv = True

$requirements

Executable     = $filename.sh
Universe       = vanilla

output = $filename.$$(Cluster).out
log = $filename.$$(Cluster).log
error = $filename.$$(Cluster).err

should_transfer_files = yes
transfer_input_files = ${project}_bundle.tar.gz
transfer_output_files = libksearch/$filename.csv

queue
""",
    'k-shortest-simple-paths': """#
# File automatically generated by condor (ksearch/libksearch)
#
# Project: $project
# Domain: $domain
# Variant: $variant
# Solver: $algorithm
#
nice_user = True
notify_user = $user
notification = Always
getenv = True

$requirements

Executable     = $filename.sh
Universe       = vanilla

output = $filename.$$(Cluster).out
log = $filename.$$(Cluster).log
error = $filename.$$(Cluster).err

should_transfer_files = yes
transfer_input_files = ${project}_bundle.tar.gz
transfer_output_files = $project/$filename.csv

queue
"""
}

# template used for generating the shell script to execute in the backend which
# depends on the type of project chosen
SHELL_FILE = {

    'libksearch': """#!/usr/bin/sh

# First things first, uncompress the bundle with the two libs to build
tar xvf ${project}_bundle.tar.gz

# -----------------------------------------------------------------------------
# This version comments out all lines for compiling and linking with libpdb
# -----------------------------------------------------------------------------
    
# # Second, build and install libpdb (only the library)
# cd libpdb
# CXX=clang++-20 CC=clang-20 cmake . -DCMAKE_BUILD_TYPE=Release
# make pdb
# cmake . -DCMAKE_INSTALL_PREFIX=/tmp
# cmake --install .

# # Make sure the libpdb is accessible to libksearch which is compiled next
# export PDB_ROOT=/tmp

# # Add include path for compiling libksearch
# export CXXFLAGS="-std=c++20 -I$$PDB_ROOT/include $$CXXFLAGS"

# # Add library path for linking libksearch
# export LDFLAGS="-L$$PDB_ROOT/lib $$LDFLAGS"

# # Make sure the runtime can find libpdb.so
# export LD_LIBRARY_PATH="$$PDB_ROOT/lib:$$LD_LIBRARY_PATH"

# # Next, build libksearch ensuring that clang++-20 is used
# cd ../libksearch

# # compile the library, remember to disable the unit tests as GTest might not be
# # available in the backend node
# cmake . -DCMAKE_C_COMPILER=clang-20 -DCMAKE_CXX_COMPILER=clang++-20 -DCMAKE_CXX_FLAGS="-std=c++20  -I/tmp/include" -DCMAKE_EXE_LINKER_FLAGS="-L/tmp/lib" -DCMAKE_PREFIX_PATH=/tmp -DCMAKE_BUILD_TYPE=Release -DDISABLE_TESTS=ON

# -----------------------------------------------------------------------------
# The following version compiles libksearch alone
# -----------------------------------------------------------------------------
    
# Next, build libksearch ensuring that clang++-20 is used
cd libksearch

# compile the library, remember to disable the unit tests as GTest might not be
# available in the backend node
cmake . -DCMAKE_C_COMPILER=clang-20 -DCMAKE_CXX_COMPILER=clang++-20 -DCMAKE_CXX_FLAGS="-std=c++23  -stdlib=libc++" -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++ -L/tmp/lib" -DCMAKE_PREFIX_PATH=/tmp -DCMAKE_BUILD_TYPE=Release -DDISABLE_TESTS=ON
    
# Compile libksearch
make VERBOSE=1 ksearch

# and now build the executable
make VERBOSE=1 $executable

# Run the executable with the given arguments but show first the current version
# and information on the cpu and memory
domains/$execdomain/$executable --version
domains/$execdomain/$executable $args
""",
    'k-shortest-simple-paths': """#!/usr/bin/sh

# First things first, uncompress the bundle with the code to compile
tar xvf ${project}_bundle.tar.gz

# Next, build k-shortest-simple-paths ensuring that clang++-20 is used
cd k-shortest-simple-paths
cmake . -DCMAKE_C_COMPILER=clang-20 -DCMAKE_CXX_COMPILER=clang++-20 -DCMAKE_BUILD_TYPE=Release

# Compile everything
make

# Run the executable with the given arguments but show first the current version
# and information on the cpu and memory
domains/$execdomain/$executable --version
domains/$execdomain/$executable $args
"""
}

# Local Variables:
# mode:python
# fill-column:80
# End:
