#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# cndmetadata.py
# Description:
# -----------------------------------------------------------------------------
#
# Started on <dom 02-08-2026 01:27:06.695866322 (1785626826)>
# Carlos Linares López <carlos.linares@uc3m.es>
#

"""
Definition of metadata used for characterizing those files generated by condor
"""

# imports
# -----------------------------------------------------------------------------
from pathlib import Path
from string import Template

import cndconf
import utils


# globals
# -----------------------------------------------------------------------------

LOGGER = utils.LOGGER

# critical
CRITICAL_UNKNOWN_DESTINATION_DIRECTORY_DOMAIN = "No destination directy registered for the domain '{}'"
CRITICAL_UNKNOWN_DESTINATION_DIRECTORY_DOMAIN_VARIANT = "No destination directy registered for the variant '{}' in the domain '{}'"
CRITICAL_UNKNOWN_DOMAIN = "Unknown domain '{}'"

# -----------------------------------------------------------------------------
# CNDMetada
#
# This class stores all the metadata of a bundle of files
# -----------------------------------------------------------------------------
class CNDMetadata:
    """This class stores all the metadata of a bundle of files

    """

    def __init__(self, domain: str, project: str, algorithm: str, variant: str, size: str, ks: str):
        """A container of metadata is created with all metadata info

        """

        # copy the attributes
        (self._domain, self._project, self._algorithm, self._variant, self._size, self._ks) = \
            (domain, project, algorithm, variant, size, ks)

    def __eq__(self, other: "CNDMetadata") -> bool:
        """return true if this instance and other contain the same metadata"""

        return self._domain == other._domain and \
            self._project == other._project and \
            self._algorithm == other._algorithm and \
            self._variant == other._variant and \
            self._size == other._size and \
            self._ks == other._ks

    def __hash__(self) -> int:
        """return a hash value for this collection of metadata"""
        
        return hash((
            self._domain,
            self._project,
            self._algorithm,
            self._variant,
            self._size,
            self._ks,
        ))
    
    def __str__(self) -> str:
        """return a human-readable version of the contents of the metadata

           The string returned depends on the domain, i.e., each domain has a
           specific string

        """

        # -- initialization
        output = ""

        if self._domain == "n-pancake" or self._domain == "n-puzzle":
            output = f"{self._size}{self._domain[2:]}.{self._project}-{self._algorithm}.{self._variant}.{self._ks}"
        elif self._domain == "roadmap":
            output = f"USA-road-d.{self._size}.{self._project}-{self._algorithm}.{self._variant}.{self._ks}"
        elif self._domain == "maps":
            output = f"random512-{self._size}-0.{self._domain}.{self._project}-{self._algorithm}.{self._variant}.{self._ks}"
        else:
            LOGGER.critical(CRITICAL_UNKNOWN_DOMAIN.format(self._domain))
            raise ValueError(CRITICAL_UNKNOWN_DOMAIN.format(self._domain))

        return output
        
    def get_domain(self) -> str:
        """return the domain"""

        return self._domain
        
    def get_project(self) -> str:
        """return the project"""

        return self._project
        
    def get_algorithm(self) -> str:
        """return the algorithm"""

        return self._algorithm
        
    def get_variant(self) -> str:
        """return the variant"""

        return self._variant
        
    def get_ks(self) -> str:
        """return the range of k values"""

        return self._ks

    def get_size(self) -> str:
        """return the size"""

        return self._size

    def get_data_dir(self) -> Path:
        """return the destination directory of the csv files corresponding to
           these metadata"""

        # the destination directory follows always the same structure, so that a
        # template is created to represent it
        path_template = Template("data/${domain}/${variant}/${size}")

        # and it now gets substituted with the suitable values
        path = Path(path_template.substitute(
            domain=self._domain,
            variant=self._variant,
            size=self._size,
        ))

        return path


# Local Variables:
# mode:python
# fill-column:80
# End:
