#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# condor_cmd.py
# Description:
# -----------------------------------------------------------------------------
#
# Started on <sáb 01-08-2026 23:38:11.566232883 (1785620291)>
# Carlos Linares López <carlos.linares@uc3m.es>
#

"""Script used to move all files generated by condor to their respective
directories, or to remove a selection of them

"""

# imports
# -----------------------------------------------------------------------------
import re
import time

from pathlib import Path

import argparser
import cndbundle
import cndcontainer
import cndmetadata
import utils


# globals
# -----------------------------------------------------------------------------

# default logger
LOGGER = utils.LOGGER

# info messages
INFO_TOTAL_NUMBER_BUNDLES = "Total number of bundles: {}"
INFO_TOTAL_NUMBER_COMPLETE_BUNDLES = "Total number of complete bundles: {}"
INFO_TOTAL_NUMBER_VALID_BUNDLES = "Total number of valid bundles: {}"

INFO_ELAPSED_TIME = "Elapsed time: {0}"

# -----------------------------------------------------------------------------
# main body
# -----------------------------------------------------------------------------
def main():

    """Main body

    """

    # -------------------------------------------------------------------------
    # --initialization

    # get the current time
    start_time = time.time()

    # invoke the parser and parse all commands
    params = argparser.createFilesArgParser().parse_args()
    
    # set the requested logging level
    LOGGER.setLevel(utils.get_logging_level(params.level))

    # create a container for storing information of all files indexed by their
    # metadata
    container = cndcontainer.CNDContainer()
    
    # get all files in the current directory
    for ifile in [path for path in Path.cwd().iterdir() if path.is_file()]:
        if cndbundle.validate_metadata(ifile):
            container += ifile

    # and show the contents of all bundles if debug messages are enabled
    LOGGER.debug(container)

    # show various statistics including the total number of bundles, and also
    # the number of them which are valid and/or complete
    LOGGER.info(INFO_TOTAL_NUMBER_BUNDLES.format(container.get_nb_bundles()))
    LOGGER.info(INFO_TOTAL_NUMBER_COMPLETE_BUNDLES.format(container.get_nb_complete_bundles()))
    LOGGER.info(INFO_TOTAL_NUMBER_VALID_BUNDLES.format(container.get_nb_valid_bundles()))

    # and now perform the correct action
    if params.command == "mv":
        container.move(params.dry_run, params.force)
    elif params.command == "rm":
        container.remove(params.dry_run,
                         params.remove_all,
                         params.remove_valid,
                         params.remove_invalid,
                         params.remove_complete,
                         params.remove_incomplete,
                         params.remove_complete_and_valid,
                         params.remove_incomplete_and_valid,
                         params.remove_complete_and_invalid,
                         params.remove_incomplete_and_invalid)
    elif params.command == "ls":
        container.list(params.all,
                       params.valid,
                       params.invalid,
                       params.complete,
                       params.incomplete,
                       params.complete_and_valid,
                       params.incomplete_and_valid,
                       params.complete_and_invalid,
                       params.incomplete_and_invalid,
                       params.domain,
                       params.project,
                       params.algorithm,
                       params.variant,
                       params.size)
    elif params.command == "tar":
        container.tar(params.archive,
                      params.all,
                      params.valid,
                      params.invalid,
                      params.complete,
                      params.incomplete,
                      params.complete_and_valid,
                      params.incomplete_and_valid,
                      params.complete_and_invalid,
                      params.incomplete_and_invalid,
                      params.domain,
                      params.project,
                      params.algorithm,
                      params.variant,
                      params.size)
        
    # show the elapsed time
    end_time = time.time()
    LOGGER.info(INFO_ELAPSED_TIME.format(utils.seconds_to_str(end_time - start_time)))
    

# main
# -----------------------------------------------------------------------------
if __name__ == '__main__':
    main()



# Local Variables:
# mode:python
# fill-column:80
# End:
