// -*- coding: utf-8 -*-
// KHSidnode_t.h
// -----------------------------------------------------------------------------
//
// Started on <lun 02-06-2025 13:18:32.354630585 (1748863112)>
// Carlos Linares López <carlos.linares@uc3m.es>
//

//
// Definition of nodes as used by sBELA*
//

#ifndef _KHSIDNODE_T_H_
#define _KHSIDNODE_T_H_

#include <vector>

#include "KHSlabelednode_t.h"

namespace khs {

    template<typename T>
    class idnode_t : public labelednode_t<T> {

        // INVARIANT: sBELA* requires nodes to be almost equal to those
        // generated by the non-simple variant (i.e., BELA*). The only necessary
        // additions consist of:
        //
        // 1. A container of path ids which are used to detect loops. Path ids
        //    consist of integer values
        std::vector<size_t> _pid;

        // 2. A boolean flag, unwound which takes the value true if and only if
        //    either no recursive call has been invoked from it, or the
        //    recursive invocation over it already backtracked
        bool _unwound;

    public:

        // Default constructors are forbidden
        idnode_t () = delete;

        // Explicit constructors
        idnode_t (const T& state, int h=0, int g=0) :
            labelednode_t<T> {            state, h, g },
            _pid             { std::vector<size_t> () },
            _unwound         {                   true }
        {}

        // Copy constructors and assignment constructors by default
        idnode_t (const idnode_t&) = default;
        idnode_t (idnode_t&&) = default;

        // getters
        [[nodiscard]] const std::vector<size_t> get_pids () const { return _pid; }
        [[nodiscard]] bool get_unwound () const { return _unwound; }

        // setters
        void set_unwound (const bool value) {
            _unwound = value;
        }

        // operators

        friend std::ostream& operator<< (std::ostream& stream, const idnode_t& node) {

            stream << " <" << node.get_state ();
            stream << ", " << node.get_g ();
            stream << " + " << node.get_h ();
            stream << " = " << node.get_f ();
            stream << "> (bp: ";
            for (auto bp: node.get_backpointers ()) {
                stream << "{" << bp.get_pointer () << ", " << bp.get_cost () << "} ";
            }
            stream << ") [gb: ";
            for (auto gb: node.get_gb ()) {
                stream << gb << " " ;
            }
            stream << " ]; [pid: ";
            for (auto pid: node.get_pids ()) {
                stream << pid << " ";
            }
            stream << "]; unwound: " << node.get_unwound ();

            return stream;
        }

        // methods

        // add the given path id to the container of pids. Note it is not
        // verified whether the pid already exists or not. It is the
        // responsibility of the caller to guarantee that that can not happen.
        void add_pid (const size_t pid) {
            _pid.push_back (pid);
        }

        // remove all path ids from this node
        void clear_pids () {
            _pid.clear ();
        }

    }; // idnode_t<T>

} // namespace khs

namespace std {

    // Definition of a hash function for idnodes. The definition is included in
    // the std namespace so that it can be used directly by the functions
    // implemented in that namespace
    template<typename T>
    struct hash<khs::idnode_t<T>> {

        // hash function
        size_t operator() (const khs::idnode_t<T>& node) const {

            // just return the hash value implemented in the hash function of
            // the underlying type which has to be defined in the std namespace
            return std::hash<T>{}(node.get_state ());
        }
    }; // struct hash<idnode_t<T>>
} // namespace std


#endif // _KHSIDNODE_T_H_

// Local Variables:
// mode:cpp
// fill-column:80
// End:
